import {db} from './firebase.js';
import {collection,getDocs} from 'https://www.gstatic.com/firebasejs/12.17.1/firebase-firestore.js';
const pages=[
 ['Home','index.html','Church home, worship, daily word, events and latest updates.'],['About Us','about.html','Vision, mission, beliefs, history and church story.'],['Leadership','leadership-board.html','Church leadership and pastoral team.'],['Ministries','ministries.html','Children, youth, men, women, prayer, worship and evangelism ministries.'],['Events','events.html','Upcoming church events and registrations.'],['Sermons','sermons.html','Latest sermons and teaching resources.'],['Audio Sermons','audio-sermons.html','Audio sermon library.'],['Daily Word','daily-word.html','Daily Bible verse and devotional reflection.'],['Holy Bible','bible.html','Read and search the King James Version Bible.'],['Prayer','prayer.html','Submit a prayer request and connect with the prayer team.'],['Testimonies','testimonies.html','Stories of what God has done.'],['Give','give.html','Ways to support the ministry.'],['Resources','resources.html','Church resources, audio and PDF materials.'],['Gallery','gallery.html','Church photos and media.'],['Live Stream','livestream.html','Watch live church services.'],['Branches','branches.html','Find all 46 Healing Tabernacle branches.'],['Plan Your Visit','visit.html','Service times, location and visitor information.'],['Contact','contact.html','Contact the church.']
];
const branches=['adjumani','apac','arua','budaka','bushenyi','busia','dokolo','entebbe','fort-portal','gulu','hoima','iganga','jinja','kabale','kampala','kamuli','kapchorwa','kasese','kayunga','kiboga','kira','kitgum','kotido','kumi','kyenjojo','lira','luwero','lyantonde','masaka','masindi','mbale','mbarara','mityana','moroto','mubende','mukono','nansana','nebbi','ntungamo','pallisa','rakai','rukungiri','soroti','tororo','wakiso','yumbe'];
const branchNames=branches.map(x=>x.replace(/-/g,' ').replace(/\b\w/g,m=>m.toUpperCase()));
const form=document.getElementById('searchForm'),q=document.getElementById('q'),results=document.getElementById('results'),status=document.getElementById('status');
function esc(s){const d=document.createElement('div');d.textContent=String(s??'');return d.innerHTML}
function render(items){results.innerHTML=items.length?items.slice(0,60).map(x=>`<a class="result" href="${x.href}"><small>${esc(x.type)}</small><h3>${esc(x.title)}</h3><p>${esc(x.text)}</p></a>`).join(''):'<div class="htm-empty">No matching results. Try a different word.</div>';status.textContent=items.length?`${Math.min(items.length,60)} results shown.`:''}
async function search(){const term=q.value.trim().toLowerCase();if(!term){render([]);status.textContent='Type something to search.';return}status.textContent='Searching…';let out=pages.filter(x=>(x[0]+' '+x[2]).toLowerCase().includes(term)).map(x=>({type:'Website page',title:x[0],text:x[2],href:x[1]}));branchNames.filter(x=>x.toLowerCase().includes(term)).forEach((x,i)=>out.push({type:'Branch',title:x+' Branch',text:'Healing Tabernacle Ministries branch',href:`branches/${branches[i]}/index.html`}));
 try{for(const c of ['sermons','events','announcements','ministries','branches']){const snap=await getDocs(collection(db,c));snap.forEach(d=>{const x=d.data();const text=[x.title,x.name,x.description,x.detail,x.location,x.speaker,x.pastor].filter(Boolean).join(' ');if(text.toLowerCase().includes(term))out.push({type:c,title:x.title||x.name||x.reference||d.id,text,href:c==='branches'?`branches/${x.slug||d.id}/index.html`:(c==='events'?'events.html':c==='sermons'?'sermons.html':c==='ministries'?'ministries.html':'index.html')})})}}catch(e){}render(out)}
form.addEventListener('submit',e=>{e.preventDefault();search()});const initial=new URLSearchParams(location.search).get('q');if(initial){q.value=initial;search()}
